name: Build

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_34_x86_64
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Spack
        uses: spack/setup-spack@v2

      - name: Install
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: spack -e . install
